### Imporing headers

In [2]:
import numpy as np
from linearmodel import LinearModel

### Example 1
Maximize $P = 5x_1 + 5x_2$ \
Subject to \
$2x_1 + x_2 \le 10$ \
$x_1 + 2x_2 \le 8$ \
$x_1, x_2 \ge 0$

In [3]:
# filling up arrays
A = np.array([[2, 1], [1, 2]])
B = np.array([10, 8])
C = np.array([5, 5])

In [4]:
# optimization
lm = LinearModel(A, B, C)
lm.optimize()

In [5]:
#the optimal simplex tableau
lm.tableau

array([[ 1.        ,  0.        ,  0.66666667, -0.33333333,  0.        ,
         4.        ],
       [ 0.        ,  1.        , -0.33333333,  0.66666667,  0.        ,
         2.        ],
       [ 0.        ,  0.        ,  1.66666667,  1.66666667,  1.        ,
        30.        ]])

In [6]:
# optimal solution of (x1, x2)
lm.optimalSoln()

array([4., 2.])

In [8]:
# optimal value of P
lm.optimalVal()

30.0

Hence the optimal value of problem is, \
$P = 30$ at $x_1 = 4, x_2 = 2$

### Example 2
Maximize $P = 30x_1 + 40x_2$ \
subject to \
$2x_1 + x_2 \le 10$ \
$x_1 + x_2 \le 7$ \
$x_1 + 2x_2 \le 12$ \
$x_1, x_2 \ge 0$

In [9]:
# filling up arrays
D = np.array([[2, 1], [1, 1], [1, 2]])
E = np.array([10, 7, 12])
F = np.array([30, 40])

In [11]:
# optimization
lm2 = LinearModel(D, E, F)
lm2.optimize()

In [12]:
#the optimal simplex tableau
lm2.tableau

array([[  0.,   0.,   1.,  -3.,   1.,   0.,   1.],
       [  1.,   0.,   0.,   2.,  -1.,   0.,   2.],
       [  0.,   1.,   0.,  -1.,   1.,   0.,   5.],
       [  0.,   0.,   0.,  20.,  10.,   1., 260.]])

In [14]:
# optimal solution of (x1, x2)
lm2.optimalSoln()

array([2., 5.])

In [15]:
# optimal value of P
lm2.optimalVal()

260.0